FROM python:3.9-slim

WORKDIR /app

# Copy the Flask application files
COPY ./flask-app /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the Flask app will run on
EXPOSE 8000

# Run the app with gunicorn as WSGI server
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
